CXXFLAGS:=-Wall -std=c++17 -O2 -DACCEPT_USE_OF_DEPRECATED_PROJ_API_H
EXECUTABLE=run_me
INCLUDEPATH=../.. /usr/include/gdal /usr/include/mysql /usr/include/postgresql
INCFLAGS=$(foreach x, $(INCLUDEPATH), -I$x)
LIBS=curl gdal mysqlclient odbc proj pq spatialite sqlite3
LDFLAGS+=$(foreach x, $(LIBS), -l$x)
OBJECTS=$(SOURCES:.cpp=.o)
SOURCES=main.cpp second_translation_unit.cpp
SQLITE_DB=drop_me.sqlite

all: $(SOURCES) $(EXECUTABLE)

$(EXECUTABLE): $(OBJECTS)
	$(CXX) $(OBJECTS) -o $@  $(LDFLAGS)

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCFLAGS) $< -o $@

test: all
	./$(EXECUTABLE)

clean:
	rm -rf *.o $(EXECUTABLE) $(SQLITE_DB)
