image:
  - Ubuntu1804
  - Visual Studio 2017

platform: x64

configuration: Release

clone_depth: 1

skip_tags: true

for:
-
  matrix:
    only:
      - image: Ubuntu1804

  services:
    - mssql
    - mysql
    - postgresql

  environment:
    COMPILER: g++-8
    DEB_NAME: "nanogis.ubuntu.1804"

  install:
    - sh: sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ bionic-pgdg main" >> /etc/apt/sources.list.d/pgdg.list.list'
    - sh: wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
    - sh: sudo apt update
    - sh: sudo apt-get -y install postgresql-12-postgis-3
    - sh: sudo add-apt-repository ppa:beineri/opt-qt-5.12.0-bionic
    - sh: sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable
    - sh: sudo apt-get update
    - sh: sudo apt-get -y install git
    - sh: sudo apt-get -y install libboost-dev
    - sh: sudo apt-get -y install libgdal-dev
    - sh: sudo apt-get -y install libgl1-mesa-dev
    - sh: sudo apt-get -y install qt512-meta-minimal
    - sh: sudo apt-get -y install qt512imageformats
    - sh: source /opt/qt512/bin/qt512-env.sh
    - ps: Invoke-WebRequest -Uri https://github.com/catchorg/Catch2/releases/download/v2.12.3/catch.hpp -OutFile $env:APPVEYOR_BUILD_FOLDER\..\catch.hpp

  build_script:
    - sh: cd $APPVEYOR_BUILD_FOLDER/example/nanogis
    - sh: qmake QMAKE_CXX=$COMPILER QMAKE_LINK=$COMPILER
    - sh: make CXX=$COMPILER LINK=$COMPILER
    - sh: cd $APPVEYOR_BUILD_FOLDER
    - sh: mkdir $APPVEYOR_BUILD_FOLDER/$DEB_NAME
    - sh: mkdir $APPVEYOR_BUILD_FOLDER/$DEB_NAME/usr
    - sh: mkdir $APPVEYOR_BUILD_FOLDER/$DEB_NAME/usr/local
    - sh: mkdir $APPVEYOR_BUILD_FOLDER/$DEB_NAME/usr/local/bin
    - sh: cp $APPVEYOR_BUILD_FOLDER/example/nanogis/nanogis $APPVEYOR_BUILD_FOLDER/$DEB_NAME/usr/local/bin
    - sh: mkdir $APPVEYOR_BUILD_FOLDER/$DEB_NAME/DEBIAN
    - sh: cp $APPVEYOR_BUILD_FOLDER/example/nanogis/control.ubuntu.1804 $APPVEYOR_BUILD_FOLDER/$DEB_NAME/DEBIAN/control
    - sh: dpkg-deb --build $APPVEYOR_BUILD_FOLDER/$DEB_NAME

  before_test:
     - sh: sudo -u postgres psql -c "ALTER USER postgres with password 'Password12!';" postgres
     - sh: psql 'host=localhost dbname=postgres user=postgres password=Password12!' -c "CREATE EXTENSION postgis;"

  test_script:
    - sh: cd $APPVEYOR_BUILD_FOLDER/test
    - sh: export CXXFLAGS="-DBARK_TEST_MYSQL_SERVER=localhost -DBARK_TEST_ODBC_MSSQL_SERVER=localhost -DBARK_TEST_POSTGRES_SERVER=localhost -DBARK_TEST_DATABASE_PWD=Password12!"
    - sh: make -f ./makefile.ubuntu test CXX=$COMPILER

  artifacts:
    - path: $(DEB_NAME).deb
      name: $(DEB_NAME).deb

  deploy:
    provider: GitHub
    auth_token:
      secure: eK6200vsXUmBfsFy8CVFVCsgBL+WDOP2j2HHHdbcEo5ToHFBljTDUWDNgFq0U5xw
    artifact: $(DEB_NAME).deb

-
  matrix:
    only:
      - image: Visual Studio 2017

  services:
    - mssql2017
    - mysql
    - postgresql101

  environment:
    NANOGIS_ARCHIVE: nanogis.windows.zip
    NANOGIS_ROOT: C:\nanogis
    OSGEO4W_ROOT: C:\OSGeo4W64
    PGUSER: postgres
    PGPASSWORD: Password12!

  install:
    - mkdir %OSGEO4W_ROOT%
    - ps: Invoke-WebRequest -Uri http://download.osgeo.org/osgeo4w/osgeo4w-setup-x86_64.exe -OutFile $env:OSGEO4W_ROOT\osgeo4w-setup-x86_64.exe
    - call %OSGEO4W_ROOT%\osgeo4w-setup-x86_64.exe -q -k -r -A -s http://download.osgeo.org/osgeo4w/ -a x86_64 -P curl,gdal,libmysql,libmysql-devel,libpq,proj,spatialite,sqlite3 -R %OSGEO4W_ROOT% > NUL
    - del /Q /F %OSGEO4W_ROOT%\bin\boost*.dll %OSGEO4W_ROOT%\bin\mod_spatialite.dll
    - call %OSGEO4W_ROOT%\bin\o4w_env.bat
    - curl -L -O -S -s http://download.osgeo.org/postgis/windows/pg10/postgis-bundle-pg10-3.0.1x64.zip
    - call "C:\Program Files\7-Zip\7z.exe" x postgis-bundle-pg10-3.0.1x64.zip > nul
    - xcopy /s /y /q postgis-bundle-pg10-3.0.1x64 "C:\Program Files\PostgreSQL\10"
    - call C:\Qt\5.12\msvc2017_64\bin\qtenv2.bat
    - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
    - ps: Invoke-WebRequest -Uri https://github.com/catchorg/Catch2/releases/download/v2.12.3/catch.hpp -OutFile $env:OSGEO4W_ROOT\include\catch.hpp
    - 'SET INCLUDE=%OSGEO4W_ROOT%\include;%OSGEO4W_ROOT%\include\libpq;%OSGEO4W_ROOT%\include\mysql;C:\Libraries\boost_1_69_0;%INCLUDE%'
    - 'SET LIB=%OSGEO4W_ROOT%\lib;%LIB%'

  build_script:
    - cd %APPVEYOR_BUILD_FOLDER%/example/nanogis
    - qmake
    - nmake

  after_build:
    - mkdir %NANOGIS_ROOT%
    - copy %APPVEYOR_BUILD_FOLDER%\example\nanogis\release\nanogis.exe %NANOGIS_ROOT%
    - windeployqt --no-quick-import --no-translations --no-system-d3d-compiler --no-webkit2 --no-opengl-sw %NANOGIS_ROOT%\nanogis.exe > NUL
    - copy %OSGEO4W_ROOT%\bin\*.dll %NANOGIS_ROOT% > NUL
    - call "C:\Program Files\7-Zip\7z.exe" a %APPVEYOR_BUILD_FOLDER%\example\%NANOGIS_ARCHIVE% %NANOGIS_ROOT%

  before_test:
    - call "C:\Program Files\PostgreSQL\10\bin\psql" -d postgres -U postgres -c "CREATE EXTENSION postgis;"

  test_script:
    - cd %APPVEYOR_BUILD_FOLDER%/test
    - SET CXXFLAGS=/DBARK_TEST_MYSQL_SERVER=localhost /DBARK_TEST_ODBC_MSSQL_SERVER=(local)\\SQL2017 /DBARK_TEST_ODBC_MYSQL_SERVER=localhost /DBARK_TEST_ODBC_POSTGRES_SERVER=localhost /DBARK_TEST_POSTGRES_SERVER=localhost /DBARK_TEST_DATABASE_PWD=Password12!&& nmake -f ./makefile.windows test

  artifacts:
    - path: example\%NANOGIS_ARCHIVE%
      name: $(NANOGIS_ARCHIVE)

  deploy:
    provider: GitHub
    auth_token:
      secure: eK6200vsXUmBfsFy8CVFVCsgBL+WDOP2j2HHHdbcEo5ToHFBljTDUWDNgFq0U5xw
    artifact: $(NANOGIS_ARCHIVE)
