language: cpp
if: tag IS present
sudo: true
dist: bionic
git:
  depth: 1
services:
  - mysql
matrix:
  include:
  - os: linux
    env: COMPILER=g++-8
    addons:
      postgresql: "10"
      apt:
        sources:
        - sourceline: ppa:beineri/opt-qt-5.12.0-bionic
        - sourceline: ppa:ubuntugis/ubuntugis-unstable
        packages:
        - g++-8
        - libboost-dev
        - libgdal-dev
        - libgl1-mesa-dev
        - postgresql-10-postgis-2.4
        - qt512-meta-minimal
        - qt512imageformats
        - doxygen
    before_script:
      - psql -U postgres -c "create extension postgis"
install:
- source /opt/qt512/bin/qt512-env.sh
script:
- wget -P $TRAVIS_BUILD_DIR/.. https://github.com/catchorg/Catch2/releases/download/v2.9.2/catch.hpp
- cd $TRAVIS_BUILD_DIR/test
- make -f ./makefile.ubuntu test CXX=$COMPILER CXXFLAGS+=-DACCEPT_USE_OF_DEPRECATED_PROJ_API_H CXXFLAGS+=-DBARK_TEST_MYSQL_SERVER=localhost CXXFLAGS+=-DBARK_TEST_POSTGRES_SERVER=localhost CXXFLAGS+=-DBARK_TEST_DATABASE_PWD=
- cd $TRAVIS_BUILD_DIR/example/nanogis
- qmake QMAKE_CXX=$COMPILER QMAKE_LINK=$COMPILER
- make CXX=$COMPILER LINK=$COMPILER
- cd $TRAVIS_BUILD_DIR
- doxygen Doxyfile
deploy:
- provider: pages
  skip_cleanup: true
  local_dir: html
  github_token: $GH_REPO_TOKEN
  on:
    tags: true
