language: cpp
if: tag IS present
sudo: true
dist: focal
git:
  depth: 1
services:
  - mysql
matrix:
  include:
  - os: linux
    env: COMPILER=g++
    addons:
      apt:
        sources:
        - sourceline: ppa:beineri/opt-qt-5.12.9-focal
        - sourceline: ppa:ubuntugis/ubuntugis-unstable
        packages:
        - g++
        - libboost-dev
        - libgdal-dev
        - libgl1-mesa-dev
        - qt512-meta-minimal
        - qt512imageformats
        - doxygen
install:
- source /opt/qt512/bin/qt512-env.sh
script:
- wget -P $TRAVIS_BUILD_DIR/.. https://github.com/catchorg/Catch2/releases/download/v2.13.3/catch.hpp
- cd $TRAVIS_BUILD_DIR/test
- export CXXFLAGS="-DBARK_TEST_MYSQL_SERVER=localhost -DBARK_TEST_DATABASE_PWD="
- make -f ./makefile.ubuntu test CXX=$COMPILER
- cd $TRAVIS_BUILD_DIR/example/nanogis
- qmake QMAKE_CXX=$COMPILER QMAKE_LINK=$COMPILER
- make CXX=$COMPILER LINK=$COMPILER
- cd $TRAVIS_BUILD_DIR
- doxygen Doxyfile
deploy:
- provider: pages
  skip_cleanup: true
  local_dir: html
  github_token: $GH_REPO_TOKEN
  on:
    tags: true
