language: cpp
sudo: true
dist: trusty

addons_shortcuts:
  addons_dev: &dev
    apt:
      sources:
        - ubuntu-toolchain-r-test
        - sourceline: 'ppa:ubuntugis/ppa'
      packages:
        - libboost-dev
        - libgdal-dev
        - libproj-dev
        - qt5-default

matrix:
  include:
    - os: linux
      env: COMPILER=g++-7
      addons: *dev
        apt:
          packages:
            - g++-7
    - os: linux
      env: COMPILER=clang++-5.0
      addons: *dev
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0

script:
  - cd ..
  - wget https://raw.githubusercontent.com/catchorg/Catch2/v2.0.1/single_include/catch.hpp
  - cd ./bark/test
  - make -f ./makefile.ubuntu test CXX=${COMPILER}
  - make -f ./makefile.ubuntu clean
  - cd ../example/nanogis
  - qmake -qt=qt5 QMAKE_CXX=${COMPILER} QMAKE_CC=${COMPILER} QMAKE_LINK=${COMPILER}
  - make CXX=${COMPILER} CC=${COMPILER} LINK=${COMPILER} CXXFLAGS+=-fPIC CFLAGS+=-fPIC
