language: cpp
sudo: true
dist: trusty

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'ppa:ubuntugis/ppa'
          packages:
            - g++-7
            - libboost-dev
            - libgdal-dev
            - libproj-dev
            - qt5-default

script:
  - cd ..
  - wget https://raw.githubusercontent.com/catchorg/Catch2/v2.0.1/single_include/catch.hpp
  - cd ./bark/test
  - make -f ./makefile.ubuntu test CXX=g++-7
  - make -f ./makefile.ubuntu clean
  - cd ../example/nanogis
  - qmake -qt=qt5 QMAKE_CXX=g++-7 QMAKE_CC=g++-7 QMAKE_LINK=g++-7 QMAKE_CXXFLAGS+=-std=c++14 QMAKE_CFLAGS+=-std=c++14
  - make CXX=g++-7 CC=g++-7 LINK=g++-7 CXXFLAGS+=-std=c++14 CFLAGS+=-std=c++14 CXXFLAGS+=-fPIC CFLAGS+=-fPIC
