language: cpp
sudo: true
dist: trusty

matrix:
  include:
    - os: linux
      addons:
        apt:
          packages:
            - libboost-dev
            - libgdal-dev

before_install:
  - git clone https://github.com/catchorg/Catch2.git

script:
  - g++ -I ".." -I "/usr/include/gdal" -I "/usr/include/mysql" -I "/usr/include/postgresql" -I "../Catch2/single_include" ./test/main.cpp ./test/second_translation_unit.cpp -lcurl -lgdal -lmysqlclient -lodbc -lproj -lpq -lspatialite -lsqlite3
