language: cpp

sudo: true

dist: trusty

git:
  depth: 1

branches:
  only:
    - master

env:
  global:
    - NANOGIS_DEB_DIR: nanogis.ubuntu 

matrix:
  include:
    - os: linux
      env: COMPILER=g++-7
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'ppa:ubuntugis/ppa'
          packages:
            - g++-7
            - libboost-dev
            - libgdal-dev
            - libproj-dev
            - qt5-default

script:
  - wget -P $TRAVIS_BUILD_DIR/.. https://raw.githubusercontent.com/catchorg/Catch2/v2.0.1/single_include/catch.hpp
  - cd $TRAVIS_BUILD_DIR/test
  - make -f ./makefile.ubuntu test CXX=$COMPILER
  - cd $TRAVIS_BUILD_DIR/example/nanogis
  - qmake -qt=qt5 QMAKE_CXX=$COMPILER QMAKE_CC=$COMPILER QMAKE_LINK=$COMPILER
  - make CXX=$COMPILER CC=$COMPILER LINK=$COMPILER CXXFLAGS+=-fPIC CFLAGS+=-fPIC
  - mkdir $TRAVIS_BUILD_DIR/example/$NANOGIS_DEB_DIR/usr
  - mkdir $TRAVIS_BUILD_DIR/example/$NANOGIS_DEB_DIR/usr/local
  - mkdir $TRAVIS_BUILD_DIR/example/$NANOGIS_DEB_DIR/usr/local/bin
  - cp $TRAVIS_BUILD_DIR/example/nanogis/nanogis $TRAVIS_BUILD_DIR/example/$NANOGIS_DEB_DIR/usr/local/bin
  - mkdir $TRAVIS_BUILD_DIR/example/$NANOGIS_DEB_DIR
  - mkdir $TRAVIS_BUILD_DIR/example/$NANOGIS_DEB_DIR/DEBIAN
  - cp $TRAVIS_BUILD_DIR/controle $TRAVIS_BUILD_DIR/example/$NANOGIS_DEB_DIR/DEBIAN
  - dpkg-deb --build $TRAVIS_BUILD_DIR/example/$NANOGIS_DEB_DIR

deploy:
  provider: releases
  api_key: tzcnc9R1Spnn0O7c24OZJUi4uYnWXx43Vbicq4PzWRBHeBCuTLveCkKvVnpWVQBF
  file: $TRAVIS_BUILD_DIR/example/$NANOGIS_DEB_DIR.deb
  skip_cleanup: true
