language: cpp
if: tag IS present
sudo: true
dist: xenial
git:
  depth: 1
env:
  global:
  - DEB_ROOT: "$TRAVIS_BUILD_DIR/nanogis.ubuntu.1604"
matrix:
  include:
  - os: linux
    env: COMPILER=g++-8
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - sourceline: ppa:mhier/libboost-latest
        - sourceline: ppa:beineri/opt-qt-5.12.0-xenial
        - sourceline: ppa:ubuntugis/ppa
        packages:
        - g++-8
        - libboost-dev
        - libgdal-dev
        - libgl1-mesa-dev
        - qt512-meta-minimal
        - qt512imageformats
        - doxygen
install:
- source /opt/qt512/bin/qt512-env.sh
script:
- wget -P $TRAVIS_BUILD_DIR/.. https://github.com/catchorg/Catch2/releases/download/v2.7.1/catch.hpp
- cd $TRAVIS_BUILD_DIR/test
- make -f ./makefile.ubuntu test CXX=$COMPILER
- cd $TRAVIS_BUILD_DIR/example/nanogis
- qmake QMAKE_CXX=$COMPILER QMAKE_CC=$COMPILER QMAKE_LINK=$COMPILER QMAKE_CXXFLAGS+=-std=c++17
- make CXX=$COMPILER CC=$COMPILER LINK=$COMPILER CXXFLAGS+=-fPIC CFLAGS+=-fPIC CXXFLAGS+=-std=c++17
- cd $TRAVIS_BUILD_DIR
- mkdir $DEB_ROOT
- mkdir $DEB_ROOT/usr
- mkdir $DEB_ROOT/usr/local
- mkdir $DEB_ROOT/usr/local/bin
- cp $TRAVIS_BUILD_DIR/example/nanogis/nanogis $DEB_ROOT/usr/local/bin
- mkdir $DEB_ROOT/DEBIAN
- cp $TRAVIS_BUILD_DIR/example/nanogis/control.ubuntu.1604 $DEB_ROOT/DEBIAN/control
- dpkg-deb --build $DEB_ROOT
- cd $TRAVIS_BUILD_DIR
- doxygen Doxyfile
deploy:
- provider: releases
  overwrite: true
  skip_cleanup: true
  target_commitish: $TRAVIS_COMMIT
  tag_name: $TRAVIS_TAG
  api_key:
    secure: fjX8rFCvW66vglC+BsO2QapYHyKrQbe7tBqo1uM/1C/KLNpf7FTHrq00nhQ8useiVl2A89Jof4+uyCcfDXP43HNasmZBX3G3kTw6lmDs/Gjj1kIb+6kOcuDFyE/a2TZp2YJlzc2y8BLOO3PMZxAxxEyCGBctgvohufXxIEJbK3r4Hi/UCwt+KPqvkjV9X84z1DESH/d6ZJgjaI37nfSPCcfkSQLuEtcLfVqVu3JWbhRZgof3gwxSz8D+YLdCIA2YXi/c+f0Op8CaVZz3Vz3j0AdpzQ0qRmcN9XmtrP5V0zhK24JML504Yjbuzftrsbb6y1cvHb6rjtaY1URAXQw9ocsHtZdkUNpfN39RjRoNTld0KYBPKU8deu/j+WFgY0QRMOqIb9veTnGLbBqSjF/oj8hPxscOSzGXvil4tl2s1f6rlWQMPOUREMAgLkOPWJpunbf7G+jUteKZfP2PkkezOl2ZxGSMSpYLs+0QOYYkdCcWyq35p2MlnW/aqu9gjSVlhkGIzFd5AfSOMyjiWTKYl2b1YRt3NNQqpnvnZALK8UmATGO31NwW0C4ptvRvbC6ukhUREnRnuO5NE03H2MPZBfIpiSkiNm64yfdFlCneNdt00qNTc54B1Aq86cv4A0s2luRtulSAbsRjLf62lueyPX6I2yZR+KFFiJzS5eh47OE=
  file:
  - "nanogis.ubuntu.1604.deb"
  on:
    tags: true
- provider: pages
  skip_cleanup: true
  local_dir: html
  github_token: $GH_REPO_TOKEN
  on:
    branch: master
