language: cpp
sudo: true
dist: trusty
git:
  depth: 1
branches:
  only:
  - master
env:
  global:
  - DEB_NAME: nanogis.ubuntu
  - DEB_ROOT: "$TRAVIS_BUILD_DIR/$DEB_NAME"
matrix:
  include:
  - os: linux
    env: COMPILER=g++-7
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - sourceline: ppa:ubuntugis/ppa
        packages:
        - g++-7
        - libboost-dev
        - libgdal-dev
        - libproj-dev
        - qt5-default
script:
- wget -P $TRAVIS_BUILD_DIR/.. https://raw.githubusercontent.com/catchorg/Catch2/v2.0.1/single_include/catch.hpp
- cd $TRAVIS_BUILD_DIR/test
- make -f ./makefile.ubuntu test CXX=$COMPILER
- cd $TRAVIS_BUILD_DIR/example/nanogis
- qmake -qt=qt5 QMAKE_CXX=$COMPILER QMAKE_CC=$COMPILER QMAKE_LINK=$COMPILER
- make CXX=$COMPILER CC=$COMPILER LINK=$COMPILER CXXFLAGS+=-fPIC CFLAGS+=-fPIC
- mkdir $DEB_ROOT
- mkdir $DEB_ROOT/usr
- mkdir $DEB_ROOT/usr/local
- mkdir $DEB_ROOT/usr/local/bin
- cp $TRAVIS_BUILD_DIR/example/nanogis/nanogis $DEB_ROOT/usr/local/bin
- mkdir $DEB_ROOT/DEBIAN
- cp $TRAVIS_BUILD_DIR/control $DEB_ROOT/DEBIAN
- dpkg-deb --build $DEB_ROOT
deploy:
  provider: releases
  file_glob: true
  api_key:
    secure: "Dut9nUwtgYTYOKKB/+vQWLrFKwYCfXtoR0Qaxa9hQM/H4kY/hXt9cA1cHr/1v4khj/WKRc8c4MpzA9s2MqLOwNYOGJOeoW2AUI5QCqOq3luz/w2AVGz30+bEs3Ku/o3VIqzcp990gqTo9wfCPJbJnN1I2lsC00ep379w36k/j78udXGYnQ0/XgP9JmxnrNiQ2rvV+FBLJ9ondN9Cw5BEYo1ZYq3i8VokhnnCMM2yk66ePa+vjYNDmrrIs6SZSo00Kyn/h82tIRoB/xMh92KRHMDuZjnaabqvIutVaaYOOOCfaZCfYFFvRCHwI0XwW0nLJz+d/WYqZSixZiUwbxgtSfIZQhcOM1IIfFg/IVsZONfXZ54768Alpn46gTEeBNl9EtAJDPD+qEkrdIs3fD19QAEuwuUhEc9tTXo0EBJZiILcGOZr4SkSM4FQKQoPtcaX90KTQ8e4YOPDYx3tHmM77+SpKo8Q2Sp8OSiv/d5nUoqTyuxzrYkkmSBhNRJVT1CrcfJ+GLf030ZQPkXA6910NjajUKoQEKebdXZDr2Cg9C1yzpQGyettR2nlMl/hnalcqIgYob/LuVRTpKIljczZ5xpxpyHrDqyuZbsMdcRNjOb29rXiSeSx/mNMqiMWAo97PExVpY9Ia5D3nELtn1KBOInIZ2yvymuKkEFkzpfy1Mw="
  file: "$DEB_NAME.deb"
  skip_cleanup: true
  on:
    tags: false
