language: cpp
sudo: true
dist: trusty

matrix:
  include:
    - os: linux
    - env: COMPILER=g++-7
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'ppa:ubuntugis/ppa'
          packages:
            - g++-7
            - libboost-dev
            - libgdal-dev
            - libproj-dev
            - qt5-default

script:
  - cd ..
  - wget https://raw.githubusercontent.com/catchorg/Catch2/v2.0.1/single_include/catch.hpp
  - cd ./bark/test
  - make -f ./makefile.ubuntu test CXX=${COMPILER}
  - make -f ./makefile.ubuntu clean
  - cd ../example/nanogis
  - qmake -qt=qt5 QMAKE_CXX=${COMPILER} QMAKE_CC=${COMPILER} QMAKE_LINK=${COMPILER}
  - make CXX=${COMPILER} CC=${COMPILER} LINK=${COMPILER} CXXFLAGS+=-fPIC CFLAGS+=-fPIC
