os: Visual Studio 2017

platform: x64

configuration: Release

environment:
  OSGEO4W_ROOT: C:\\OSGeo4W64

matrix:
  fast_finish: true

shallow_clone: true
clone_depth: 1

install:
  - mkdir %OSGEO4W_ROOT%
  - ps: wget http://download.osgeo.org/osgeo4w/osgeo4w-setup-x86_64.exe --directory-prefix="$env:OSGEO4W_ROOT"
  - call %OSGEO4W_ROOT%\osgeo4w-setup-x86_64.exe -q -k -r -A -s http://download.osgeo.org/osgeo4w/ -a x86_64 -P curl,gdal,libmysql,libmysql-devel,libpq,proj,spatialite,sqlite3 -R %OSGEO4W_ROOT%
  - ps: wget https://raw.githubusercontent.com/catchorg/Catch2/v2.0.1/single_include/catch.hpp --directory-prefix="$env:OSGEO4W_ROOT\include"
  - call %OSGEO4W_ROOT%\bin\o4w_env.bat
  - call C:\Qt\5.10.1\msvc2017_64\bin\qtenv2.bat
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - 'set INCLUDE=%OSGEO4W_ROOT%\include;%OSGEO4W_ROOT%\include\libpq;%OSGEO4W_ROOT%\include\mysql;C:\Libraries\boost_1_66_0;%INCLUDE%'
  - 'set LIB=%OSGEO4W_ROOT%\lib;%LIB%'

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%/example/nanogis
  - qmake
  - nmake

test_script:
  - cd %APPVEYOR_BUILD_FOLDER%/test
  - nmake /f makefile.windows test
  - nmake /f makefile.windows clean
